---
title: "GRIN"
output: html_document
date: "2024-09-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)   
library(rgbif)
library(dplyr)
library(terra)
library(geodata)
library(sf)
citation(package = "rgbif")
```
```{r}
GRIN_DATA<-read_csv("GRIN Dataset.csv")
```
```{r}
#unique(GRIN_DATA$`geographic source`)
GRIN_species<-unique(GRIN_DATA$`host plant name`)
write_csv(GRIN_species %>% as.data.frame(),"unique_GRIN_species.csv")

#check if GBIF
check_GBIF_names<-name_backbone_checklist(name_data = GRIN_species, verbose = TRUE)
nodulating_species_GBIF_numbers<-unique(check_GBIF_names$speciesKey) %>% na.omit()
```

```{r}
GBIF_trial<-occ_search(speciesKey = nodulating_species_GBIF_numbers[1])

```


```{r}
# make big GBIF dataset
DATA_nodulating<-c()
for (i in nodulating_species_GBIF_numbers) {
  GBIF_temp<-occ_search(speciesKey = i)
  GBIF_temp<-GBIF_temp$data
  DATA_nodulating<-DATA_nodulating %>% bind_rows(GBIF_temp)
  
}

```
```{r}
# how would I plot all these occurrence records on a map (should I?)
#DATA_nodulating<-read_csv("Data_nodulation_occurence.csv")
DATA_nodulating_mini<-cbind(DATA_nodulating$scientificName, DATA_nodulating$decimalLongitude,DATA_nodulating$decimalLatitude, DATA_nodulating$geodeticDatum) %>% as.data.frame() %>% na.omit()
colnames(DATA_nodulating_mini)<-c('species','lon','lat','gd')

rm(DATA_nodulating)

DATA_nodulating_micro<-head(DATA_nodulating_mini,2000) %>% as.data.frame() %>% na.omit()

point_locations<-st_geometry(st_as_sf(DATA_nodulating_mini, coords = c("lon","lat"),crs='WGS84'))
point_locations_micro<-st_geometry(st_as_sf(DATA_nodulating_micro, coords = c("lon","lat"),crs='WGS84'))

plot(point_locations)

occurrenceplot<-ggplot()+
  geom_sf(data=point_locations,size=0.1)
occurrenceplot
```

```{r}


#download monthly temperature and precipitation
# TEMP <- geodata::worldclim_global(var = "tavg", #average temperature
#                                   res = 10, #10 minutes
#                                   path = "~/Downloads") 

#in principle monthly average precipitation might be a good starting point
Precip <- geodata::worldclim_global(var = "prec", #precipitation
                                  res = 10, #2.5minutes
                                  path = "~/Downloads") 
plot(Precip)
Bioclim <- geodata::worldclim_global(var = "bio", #precipitation
                                  res = 10, #10minutes
                                  path = "~/Downloads") 
plot(Bioclim)


AVGTEMP<-Bioclim$wc2.1_10m_bio_1
TEMPVARIANCE<-Bioclim$wc2.1_10m_bio_4
AVGPRECIP<-Bioclim$wc2.1_10m_bio_12
PRECIPVARIANCE<-Bioclim$wc2.1_10m_bio_15


plot(AVGPRECIP)
plot(point_locations, add=TRUE, pch=20,col=alpha("red",0.1),cex=0.1)

plot(log(AVGPRECIP))
plot(point_locations, add=TRUE, pch=20,col=alpha("red",0.1),cex=0.1)

ggplot()+
  stat_spatraster(data=PRECIPVARIANCE)+
  geom_sf(data=point_locations,size=0.1,color=alpha("darkred",0.05))
  

```

```{r}
#now we want to extract the monthly prec values for ?? each of the observation points for each species? or make a range shapefile and extract averages? 


DATA_nodulating_mini$temp_avg<-terra::extract(AVGTEMP,vect(point_locations))$wc2.1_10m_bio_1
DATA_nodulating_mini$temp_var<-terra::extract(TEMPVARIANCE,vect(point_locations))$wc2.1_10m_bio_4
DATA_nodulating_mini$prec_avg<-terra::extract(AVGPRECIP,vect(point_locations))$wc2.1_10m_bio_12
DATA_nodulating_mini$prec_var<-terra::extract(PRECIPVARIANCE,vect(point_locations))$wc2.1_10m_bio_15

ggplot(DATA_nodulating_mini)+
  geom_point(aes(x=prec_avg,y=temp_avg),color=alpha("darkred",0.01))

ggplot(DATA_nodulating_mini%>% filter(prec_avg<500))+
  geom_point(aes(x=prec_avg,y=temp_avg),color=alpha("darkred",0.01))

```
```{r}
#bioclim data?? do i use bioclim on the data or do i use bioclim to get the data--I did some reading on bioclim and it's unclear to me
```



